version: '3.7'
services:
  jenkins:
    user: root
    container_name: jenkins
    image: 'jenkins/jenkins:2.242'
    restart: always
    networks:
      - cicd
    environment:
      - TZ=Asia/Shanghai
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - /usr/local/data/jenkins/data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /bin/docker:/bin/docker  # linux使用
#      - /usr/local/bin/docker:/bin/docker # mac使用
networks:
  cicd:
    external:
      name: cicd